# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# More versions available at: https://legacyfabric.net/usage.html
minecraft_version=1.13.2
yarn_build=571
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.2
maven_group=fr.atesab
archives_base_name=HorseDebug

# Dependencies
# Legacy Fabric API
# Check availability for your MC version at https://legacyfabric.net/usage.html
# fabric_version=1.12.0+1.8.9
