modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/ate47/HorseInfo/issues"
license="GPL 3"
[[mods]]
	modId="horsedebug"
	version="1.2.3"
	displayName="Horse debug info"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/horse-debug-info"
	logoFile="logo.png"
	authors="ATE47"
	description="Show horse info on debug scren"

[[dependencies.horsedebug]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"