name: Bug Report 🔥
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to improve this repository!
  - type: checkboxes
    id: optishit
    attributes:
      label: The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)
      options:
      - label: "Yes, I don't have Optifine install."
        required: true
  - type: input
    id: version
    attributes:
      label: Mod version
      description: Mod version
      placeholder: "1.1.1"
    validations:
      required: true
  - type: input
    id: version_mc
    attributes:
      label: Minecraft version
      description: Minecraft version
      placeholder: "1.18"
    validations:
      required: true
  - type: dropdown
    id: dropdown_ml
    attributes:
      label: Mod loader
      description: Mod loader
      options:
        - "Fabric"
        - "Forge"
        - "Both"
        - "Other (write it in the next field)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the issue
      description: Small description of the issue
      placeholder: |
        my problem is...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Excepted behavior
      description: What was the excepted behavior?
      placeholder: |
        I was excepting...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Obtained behavior
      description: What is the obtained behavior?
      placeholder: |
        ...but this happened
    validations:
      required: false
  - type: textarea
    attributes:
      label: How to reproduce
      description: How to reproduce?
      placeholder: |
        - step 1: that
        - step 2: this
        - step 3: something
        - ...
    validations:
      required: false
  - type: dropdown
    id: dropdown_id
    attributes:
      label: Do I want to contribute to fix it?
      description: Do I want to contribute to fix it?
      options:
        - "Yes"
        - "No"
        - "Maybe"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Something else?
      description: Something else to inform us?
    validations:
      required: false
